using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class TutorialData : MonoBehaviour
{
    [System.Serializable]
    public class Page
    {
        public string title;
        public string content;
        public bool showExitButton = false;
        public bool imgMenu, imgPrev, imgNext, imgPinch, imgPointer = false;
        public bool bookCursor, sommonCursor, cauldronCursor, shelfCursor, boardCursor, orderCursor, deliverCursor = false;
        public int shownImgIdx;
        public bool poison1, poison2a, poison2b, poison = false;
    }

    [System.Serializable]
    public class Section
    {
        public string sectionTitle;
        public List<Page> pages;
    }

    public List<Section> sections = new List<Section>
    {
        new Section
        {
            sectionTitle = "INTRO",
            pages = new List<Page>
            {
                new Page {
                    title = "LULU'S",
                    showExitButton = false,
                    content = "Now, you will first read a series of instructions of the game. Please follow the instructions to try to finish a round. When reading the tutorial, you can follow the finger pointing icon to look for items. \nYou can open this toturial at anytime during the game agian using the open menu hand gesture.",
                    imgMenu = true,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = false,
                    deliverCursor = false,
                    imgPointer = true,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                },
                new Page {
                    title = "OVERVIEW",
                    showExitButton = false,
                    content = "In this game, you are a chef being cursed. You need to complete a certain number of food orders each day, deliver them to the customers in front of you, and survive for 7 days. ",
                    imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = false,
                    deliverCursor = false,
                    shownImgIdx = 0,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,


                }
            }
        },
        new Section
        {
            sectionTitle = "BOARDS",
            pages = new List<Page>
            {
                new Page {
                    title = "Order Board",
                    showExitButton = false,
                    content = "On the right side of the window, you can see an Order Board. It will display the current customer's order. The customer will request a specific dish or flavor. \nYou need to complete the order. If it's a dish, then prepare the corresponding dish. If it's a flavor, then you need to prepare a dish that has that flavor.",
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = true,
                    deliverCursor = false,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,

                },
                new Page {
                    title = "Requirement Board",
                    showExitButton = false,
                    content = "However, Cthulhu, the owner of this restaurant, might dislike certain customers. It might dislike customers wearing glasses, a beard¡­etc. Hence, it will require you to poison the dishes to torture them. ",
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = false,
                    deliverCursor = false,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                },
                new Page {
                    title = "Requirement Board",
                    showExitButton = false,
                    content = "On the Cthulhu¡¯s Requirement Board on the left side of the room, Cthulhu will tell you about the types of people to be tortured and what kind of torture it wants them to experience. \nYou need to determine if each customer matches one of these attributes. If they are, you need to poison their dish with the corresponding effect.",
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = true,
                    orderCursor = false,
                    deliverCursor = false,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                },
                new Page {
                    title = "Sanity",
                    content = "You don't belong here. \nUnder Cthulhu's influence, you will gradually be assimilated, turning into a monster like the customers. Therefore, you will lose a portion of your sanity each day. \nAlso, every time you fail to deliver a dish or poison the customers, you will lose sanity. \nLook to the blackboard on the left side of the room. Initially, your sanity will be 100. If your sanity drops to 0, you will fail. You need to maintain your sanity over these 7 days.",
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = true,
                    orderCursor = false,
                    deliverCursor = false,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                },
            }
        },
        new Section
        {
            sectionTitle = "COOKING",
            pages = new List<Page>
            {
                new Page {
                    title = "COOKING",
                    showExitButton = false,
                    content = "Continue reading for cooking instructions.",
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = false,
                    deliverCursor = false,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                },
                new Page {
                    title = "FIND THE ORDER",
                    showExitButton = false,
                    content = "Look at the Order Board. The first order is a Jelly Field.",
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = true,
                    deliverCursor = false,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                },
                new Page {
                    title = "RECIPE BOOK",
                    showExitButton = false,
                    content = "You can see the book on the right side of the room.",
                    imgPrev = false,
                    imgNext = false,
                     imgMenu = false,
                    imgPinch = false,
                    bookCursor = true,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = false,
                    deliverCursor = false,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                },
                new Page {
                    title = "RECIPE BOOK",
                    showExitButton = false,
                    content = "Flip through the book using the hand gesture below. \nLook into the recipe book for the Jelly Field. Since the customer does not request a flavor, the ¡°Sour¡± flavor does not matter.",
                    imgPrev = true,
                    imgNext = true,
                     imgMenu = false,
                    imgPinch = false,
                    bookCursor = true,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = false,
                    deliverCursor = false,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                },
                new Page {
                    title = "SHELF",
                    showExitButton = false,
                    content = "Look at the shelf behind you for ingredients. You only have a limited amount of ingredients, so don¡¯t waste them! \nUse the hand gesture below to grab the ingredient. Any items that you lose will respawn on the table to the left.",
                    imgPinch = true,
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = true,
                    boardCursor = false,
                    orderCursor = false,
                    deliverCursor = false,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                },
                new Page {
                    title = "SUMMONING TABLE",
                    showExitButton = false,
                    content = "Once you¡¯ve grabbed all the ingredients you need, collect them on the summoning table to summon a dastardly dish.",
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = false,
                    sommonCursor = true,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = false,
                    deliverCursor = false,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                },
            }
        },
        new Section
        {
            sectionTitle = "POISON",
            pages = new List<Page>
            {
                new Page {
                    title = "POISON MAKING",
                    showExitButton = false,
                    content = "Continue reading for poirson making instructions.",
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    deliverCursor = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = false,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                },
                new Page {
                    title = "FIND THE REQUIREMENTS",
                    showExitButton = false,
                    content = "Look at the Requirement Board on the left. You need to poison any customers with Beard. Cthulhu wants those customers to cry.",
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = true,
                    orderCursor = false,
                    deliverCursor = false,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                },
                new Page
                {
                    title = "CUSTOMER",
                    showExitButton = false,
                    content = "Look at the customer outside the window. It is apparent that they have a beard. You need to poison their food with the poison that makes them cry.",
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = false,
                    deliverCursor = true,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                },
                new Page
                {
                    title = "RECIPE BOOK",
                    showExitButton = false,
                    content = "First, find the poison you need in the book. \nIn this case, you need a poison that makes the customers cry. You should be able to find the recipe for the poison.",
                     imgMenu = false,
                    imgPrev = true,
                    imgNext = true,
                    imgPinch = false,
                    bookCursor = true,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = false,
                    deliverCursor = false,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                },
                new Page
                {
                    title = "POISON",
                    showExitButton = false,
                    content = "Then, next to the summoning table, you can see a cauldron and many bottles besides it. Those colorful bottles are the poisons.",
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = true,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = false,
                    deliverCursor = false,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                },
                new Page
                {
                    title = "CAULDRON",
                    showExitButton = false,
                    content = "You need to make the poison using the cauldron. Everytime you completely pour the poison into the cauldron, the liquid inside will change color. ",
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = true,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = false,
                    deliverCursor = false,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                },
                new Page
                {
                    title = "POURING",
                    showExitButton = false,
                    content = "Try to make the poison now.",
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = false,
                    deliverCursor = false,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                },
                new Page
                {
                    title = "POURING",
                    showExitButton = false,
                    content = "1. FIND POISON \nRefer to the recipe book to find the corresponding poisons you need to make a poison. \nIn this case, the poisons needed are Sulfuric Acid and Tartaric Acid. You can check if the colors of the poison match after pouring into the cauldron. The default effectless state of the poison is blue.",
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = true,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = false,
                    deliverCursor = false,
                    imgPointer = false,
                    poison1 = true,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                },
                new Page
                {
                    title = "POURING",
                    showExitButton = false,
                    content = "2. FIND MAGIC POISON SAUCE \nPick the magical rainbow bottle. This is the Magic Poison Sauce. You have to add the sauce after you pour all the needed poisons. \nIf the poisons inside the cauldron fit any of the poison recipes, the liquid inside will turn into green. Otherwise it will turn to effectless blue water.",
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = false,
                    deliverCursor = false,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = true,
                    poison2b = false,
                    poison = false,
                },
                new Page
                {
                    title = "POURING",
                    showExitButton = false,
                    content = "2. FIND MAGIC POISON SAUCE \nBe careful when you are pouring the sauce. If you pour the sauce into the cauldron with finished poison inside, the poison will be resetted to effectless. Also, if you follow the wrong recipe, you can use the sauce to reset the poison and make the new one again.",
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = false,
                    deliverCursor = false,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = true,
                    poison = false,
                },
                new Page
                {
                    title = "POURING",
                    showExitButton = false,
                    content = "3. LADLE \nOnce you get your poison finished, use the ladle to scoop up the poison and pour it onto the dish.",
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = false,
                    deliverCursor = false,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = true,
                },
            }

        },
        new Section
        {
            sectionTitle = "DELIVERING",
            pages = new List<Page>
            {
                new Page
                {
                    title = "DELIVERY TABLE",
                    showExitButton = false,
                    content = "Finally, your dish is complete with poisons! \nTurn to the window. On the Delivery Table, you can see a timer. It is currently off. \nIn the actual game, each order will have a countdown, which will be displayed here. \nCustomers are not patient. If you do not deliver the dish on time, they will be angry at you; you will lose sanity. \nNow, deliver the dish to the customer by setting it at the delivery table in front of the customer. ",
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = false,
                    deliverCursor = true,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                },
                new Page
                {
                    title = "CUSTOMER REACTION",
                    showExitButton = false,
                    content = "Now wait for the customer to react strongly to the dish, and check if it has the desired effect.",
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = false,
                    deliverCursor = true,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                },
                new Page
                {
                    title = "SANITY",
                    showExitButton = false,
                    content = "If you did it correctly, you will stay sane for another day. Try to stay sane for 7 days in the actual game. \nHave fun in your ventures, chef.",
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = false,
                    deliverCursor = false,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                },
            }
        },
        new Section
        {
            sectionTitle = "CREDITS",
            pages = new List<Page>
            {
                new Page
                {
                    title = "Credits",
                    showExitButton = false,
                    content = "PRODUCER / PROGRAMMER: Jason Chen \n" + "PROGRAMMER: Ana(Yunhan) Jiang \n" +
                              "3D MODELER / 2D ARTIST: Mia Liu \n" + "3D TEXTURER / 2D ARTIST: Britney Yang \n" + 
                              "SOUND DESIGNER: Pierre(Yizhi) Chen",
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = false,
                    deliverCursor = false,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                }
            }
        },
        new Section
        {
            sectionTitle = "MENU",
            pages = new List<Page>
            {
                new Page
                {
                    title = "",
                    content = "",
                    showExitButton = true,
                     imgMenu = false,
                    imgPrev = false,
                    imgNext = false,
                    imgPinch = false,
                    bookCursor = false,
                    sommonCursor = false,
                    cauldronCursor = false,
                    shelfCursor = false,
                    boardCursor = false,
                    orderCursor = false,
                    deliverCursor = false,
                    imgPointer = false,
                    poison1 = false,
                    poison2a = false,
                    poison2b = false,
                    poison = false,
                }
            }
        }
    };




}


